<a href="https://colab.research.google.com/github/cristiandarioortegayubro/BDS/blob/main/modulo.01/bds_python_001_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BDS/blob/main/images/Logo%20BDS%20Horizontal%208.png?raw=true">
</p>


# **<font color="DeepPink">Fundamentos de programacion en Python</font>**

<p align="center">
<img src="https://www.python.org/static/community_logos/python-powered-h-70x91.png">
</p>


<p align="justify"><b>
<font color="DeepPink">
💗 Todo el mundo deberia aprender a programar, porque te enseña a pensar...
</font>
</p>
<p align="right"><b>
<font color="DeepPink">
Steve Jobs (1995)
</font>
</p>
<br>
<br>



# **<font color="DeepPink">Introducción de la programación</font>**

<p align="justify">
La programación es el proceso que se utiliza para diseñar e implementar un programa, valiéndose de algún lenguaje que permita comunicar una serie de acciones que se requiere que la computadora realice. Podemos pensar que es una caja negra que recibe alguna información, la cual es llamada "input" (entrada), realiza alguna acción, y devuelve información, la cual es llamada "output" (salida).</p>

<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BDS/blob/main/images/Image_0004.jpg?raw=true" width="600" height="">
</p>


<p>
<font color="DeepPink">

**👀 Antes que nada, verificamos la versión de Python con la cual estamos trabajando...**

</font>
</p>

In [ ]:
!python3 -V

Python 3.9.16


<p align="justify">
Ahora si, antes de avanzar con el desarrollo de los contenidos, veamos un pequeño ejemplo de programación en Python. Este programa es un simple adivinador de números.</p>

In [ ]:
secret_number = 20

while True:
  number = input('Adivina el número secreto: ')
  try:
    number = int(number)
  except:
    print('Lo siento, este no es el número')
    continue
 
  if number != secret_number:
    if number > secret_number:
      print(number, 'Este número es mas grande que el número secreto')
 
    elif number < secret_number:
      print(number, 'Este número es mas chico que el número secreto')
  else:
    print('Adivinaste el número:', secret_number)
    break

Adivina el número secreto: 20
Adivinaste el número: 20


## **<font color="DeepPink">Lenguajes de programación</font>**

<p align="justify">
Un lenguaje de programación es un lenguaje formal que proporciona una serie de instrucciones, las cuales permiten a un programador escribir secuencias de órdenes para controlar el comportamiento físico y lógico de una computadora, con el objetivo de que produzca diversas acciones deseadas por el programador y por los usuarios.<br><br>Algunos de los lenguajes mas populares en los últimos tiempos son Python, Java, C++, JavaScript, etc.</p>

## **<font color="DeepPink">Python: el lenguaje de programación más utilizado en la actualidad</font>**

<p align="justify">
Python es un lenguaje de programación creado por por el informático holandés Guido van Rossum a principios de los años 90 para administrar sistemas operativos, concretamente el sistema operativo Amoeba. Sus construcciones lingüísticas y su enfoque orientado a objetos tienen como objetivo ayudar a los programadores a escribir código claro y lógico para proyectos pequeños y grandes. Python es un lenguaje similar a Perl, pero con una sintaxis muy limpia.<br><br>Python es un lenguaje de tipado dinámico, es decir, que los tipos de datos se asignan a las variables durante su uso, y no durante la escritura o compilación de los programas y de los scripts.
Por eso es muy fácil trabajar con este lenguaje y crear programas flexibles, que se modifiquen sobre la marcha de su ejecución.<br><br> Según el índice TIOBE, el lenguaje más utilziado del mundo en la actualidad es Python. Python ha estado en la cima del índice TIOBE durante los últimos años y ha experimentado un crecimiento significativo en popularidad durante la última década. De hecho, la popularidad de Python se ha triplicado desde 2010, lo que lo convierte en el lenguaje de programación de más rápido crecimiento.
</p>


Python es:
- un lenguaje interpretado o de script,
- con tipado dinámico,
- fuertemente tipado,
- multiplataforma y
- orientado a objetos.


### **<font color="DeepPink">Lenguaje interpretado o de script</font>**

<p align="justify">
Un lenguaje interpretado o de script es aquel que se ejecuta utilizando un programa intermedio llamado intérprete, en lugar de compilar el código a lenguaje máquina que pueda comprender y ejecutar directamente una computadora (lenguajes compilados).<br><br>
La ventaja de los lenguajes compilados es que su ejecución es más rápida. Sin embargo los lenguajes interpretados son más flexibles y más portables.
Python tiene, no obstante, muchas de las características de los lenguajes compilados, por lo que se podría decir que es semi interpretado.</p>

### **<font color="DeepPink">Con tipado dinámico</font>**

<p align="justify">
La característica de tipado dinámico se refiere a que no es necesario declarar el tipo de dato que va a contener una determinada variable, sino que su tipo se determinará en tiempo de ejecución según el tipo del valor al que se asigne, y el tipo de esta variable puede cambiar si se le asigna un valor de otro tipo.</p>

### **<font color="DeepPink">Fuertemente tipado</font>**

<p align="justify">
No se permite tratar a una variable como si fuera de un tipo distinto al que tiene, es necesario convertir de forma explícita dicha variable al nuevo tipo previamente. <br><br>Por ejemplo, si tenemos una variable que contiene un texto (variable de tipo cadena o string) no podremos tratarla como un número (sumar la cadena “9” y el número 8). <br><br>En otros lenguajes el tipo de la variable cambiaría para adaptarse al comportamiento esperado, aunque esto es más propenso a errores.</p>

### **<font color="DeepPink">Multiplataforma</font>**

<p align="justify">
El intérprete de Python está disponible en multitud de plataformas (UNIX, Solaris, Linux, DOS, Windows, OS/2, Mac OS, etc.) por lo que si no utilizamos librerías específicas de cada plataforma, nuestro programa podrá correr en todos estos sistemas operativos sin grandes cambios.</p>

### **<font color="DeepPink">Orientado a objetos</font>**

<p align="justify">
La orientación a objetos es un paradigma de programación en el que los conceptos del mundo real relevantes para nuestro problema se trasladan a clases y objetos en nuestro programa. La ejecución del programa consiste en una serie de interacciones entre los objetos.</p>

## **<font color="DeepPink">Programación orientada a objetos (POO)</font>**

<p align="justify">
Entonces, la programación orientada a objetos es un paradigma de programación que divide los componentes de un programa en objetos. En Python los objetos suelen tener <b>atributos</b> (datos asociados al objeto) y <b>métodos</b> (funciones asociadas con un objeto que pueden tener acceso a los datos internos del objeto). Es decir, el estado del objeto se define a través de variables llamadas atributos, mientras que la funcionalidad se modela a través de funciones a las que se les conoce con el nombre de métodos del objeto. <br><br>En Python todo es un objeto. <br><br>Una característica importante del lenguaje Python es la consistencia de su modelo de objetos. Cada número, cadena de caracteres, estructura de datos (tuplas, listas, diccionarios, conjuntos, etc.), función, clase, módulo, etc. tiene su propia "caja", que se denomina objeto de Python. Por lo general el paradigma orientado a objetos resulta adecuado cuando queremos agrupar estados (datos) y comportamiento (código) juntos en prácticos paquetes de funcionalidad.<br><br> Los marcos de trabajo y bibliotecas de Python utilizan este paradigma para construir su código base. Algunos ejemplos son Django, Pandas, Scikit-learn, NumPy y TensorFlow. <br><br>A continuación, veamos algunos ejemplos de objetos:
</p>

In [ ]:
#número
number = 10

In [ ]:
#cadena de caracteres
string = "Python"

In [ ]:
#tupla
tuple = (1,2,3,4,5)

In [ ]:
#lista
list1 = [1,2,3,4,5]

In [ ]:
#lista de 7 números generados aleatoriamente a partir de una distribuación normal estándar
import numpy as np
list2 = [np.random.standard_normal() for i in range(7)]

In [ ]:
#vector de 3 elementos
array1 = np.array([1,3,5])
print("Vector\n", array1)

#matriz de 2 x 3
array2 = np.array([[1,5,9],[2,6,8]])
print("\nMatriz\n", array2)

Vector
 [1 3 5]

Matriz
 [[1 5 9]
 [2 6 8]]


In [ ]:
import pandas as pd

#Dataframe
df1 = pd.DataFrame({"Edad":[30, 40, 50],
                   "Salario": [40000, 38000, 50000]
                   })
df1

Edad  Salario
0    30    40000
1    40    38000
2    50    50000

In [ ]:
df2 = pd.DataFrame(array2, columns=['col_1', 'col_2', 'col_3'])
df2

col_1  col_2  col_3
0      1      5      9
1      2      6      8

<p align="justify">
<b>Nota</b>: algunos tipos de objetos de Python son más legibles cuando son impresos usando la función integrada de Python <code>print</code>, otros no. <br><br>Veamos algunos ejemplos: </font>




In [ ]:
list2

[0.20471840330147706,
 -1.1346954956025752,
 -1.6564546822812831,
 1.587310754830892,
 -1.8029717369020897,
 0.5080004354031251,
 0.8760076781630567]

In [ ]:
print(list2)

[0.20471840330147706, -1.1346954956025752, -1.6564546822812831, 1.587310754830892, -1.8029717369020897, 0.5080004354031251, 0.8760076781630567]


In [ ]:
array2

array([[1, 5, 9],
       [2, 6, 8]])

In [ ]:
print(array2)

[[1 5 9]
 [2 6 8]]


In [ ]:
df1

Edad  Salario
0    30    40000
1    40    38000
2    50    50000

In [ ]:
print(df1)

   Edad  Salario
0    30    40000
1    40    38000
2    50    50000


## **<font color="DeepPink">Métodos y atributos</font>**

### **<font color="DeepPink">Método</font>**

Son las funciones asociadas al objeto. Se accede a los métodos a través de la sintaxis `obj.method_name`.

In [ ]:
string.upper()

'PYTHON'

In [ ]:
array1.max()

5

In [ ]:
list1.append(6)
list1

[1, 2, 3, 4, 5, 6]

In [ ]:
df2.rename(columns={"col_1":"Columna_1",
                    "col_2":"Columns_2",
                    "col_3":"Columna_3"}, 
           inplace=True)
df2

Columna_1  Columns_2  Columna_3
0          1          5          9
1          2          6          8

### **<font color="DeepPink">Atributo</font>**

<p align="justify">
Los atributos de datos definen el estado del objeto. En otros lenguajes son conocidos simplemente como atributos. 
Son datos asociados al objeto. Se accede a los atributos a través de la sintaxis <code>obj.attribute_name</code>.</p>

In [ ]:
array2.shape

(2, 3)

In [ ]:
print("La matriz es de ", array2.shape[0], "x", array2.shape[1])

La matriz es de  2 x 3


## **<font color="DeepPink">Introspección</font>**

Usando el signo de interrogación (`?`) antes o después de un objeto mostrará su información general.

In [ ]:
?array1

In [ ]:
df1?

Si el objeto es una función, usando `?` también se mostrará la documentación si está definida. 

In [ ]:
#función
print?

<p align="justify">
Si creamos una función cualquiera, para agregar esta documentación es necesario abrir y cerrar con tres comillas (simples o dobles). La creación de funciones y clases serán desarrolladas más adelante en este módulo.</p>

In [ ]:
def add_numbers(a, b):
    '''
    Add two numbers together

    Returns
    -------
    the_sum : type of arguments
    '''
    return a + b

## **<font color="DeepPink">Referencias dinámicas y tipado</font>**

<p align="justify">
Las variables en Python no tienen un tipo inherente asociado con ellas; una variable puede hacer referencia a un tipo diferente de objeto simplemente haciendo una asignación.</p>

In [ ]:
a = 5
type(a)

int

In [ ]:
b = "5"
type(b)

str

In [ ]:
c = [1,2,3]
type(c)

list

<p align="justify">
Las variables son nombres de objetos, la información de tipo se almacena en el propio objeto.</p>

Realicemos la siguiente operación matemática:

In [ ]:
5 + '5'

TypeError: ignored

<p align="justify">
!Esta operación genera un error! En algunos lenguajes, la cadena de caracteres <code>'5'</code> puede convertirse implícitamente en un número entero, lo que genera <code>10</code>. En otros, el número entero <code>5</code> puede convertirse en una cadena, lo que genera la cadena concatenada <code>'55'</code>. <br><br>En Python, tales conversiones implícitas no están permitidas. En este sentido decimos que Python es un lenguaje <b>fuertemente tipado</b>, lo que significa que cada objeto tiene un tipo específico.</p>

<p align="justify">
Es importante conocer el tipo de un objeto. También puede verificar que un objeto es una instancia de un tipo particular usando la función <code>isinstance</code>.

In [ ]:
isinstance(a, int)

True

<p align="justify">
<code>isinstance</code> puede aceptar una tupla de tipos si desea verificar que el tipo de un objeto se encuentra entre los presentes en la tupla:</p>

In [ ]:
isinstance(a, (int, float))

True

<br>
<br>
<p align="center"><b>
💗
<font color="DeepPink">
Hemos llegado al final de nuestro colab, a seguir codeando...
</font>
</p>


<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BDS/blob/main/images/Logo%20BDS%20Horizontal%208.png?raw=true">
</p>

---